# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import micro_service_pb2 as protos_dot_micro__service__pb2


class MicroServiceStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoMicro = channel.unary_unary(
                '/protos.MicroService/DoMicro',
                request_serializer=protos_dot_micro__service__pb2.DoMicroReq.SerializeToString,
                response_deserializer=protos_dot_micro__service__pb2.DoMicroResp.FromString,
                )


class MicroServiceServicer(object):
    """定义服务
    """

    def DoMicro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MicroServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoMicro': grpc.unary_unary_rpc_method_handler(
                    servicer.DoMicro,
                    request_deserializer=protos_dot_micro__service__pb2.DoMicroReq.FromString,
                    response_serializer=protos_dot_micro__service__pb2.DoMicroResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.MicroService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MicroService(object):
    """定义服务
    """

    @staticmethod
    def DoMicro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.MicroService/DoMicro',
            protos_dot_micro__service__pb2.DoMicroReq.SerializeToString,
            protos_dot_micro__service__pb2.DoMicroResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
