# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/micro_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import base_pb2 as protos_dot_base__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/micro_service.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aprotos/micro_service.proto\x12\x06protos\x1a\x11protos/base.proto\"\xdf\x01\n\x04\x44\x61ta\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1e\n\x01m\x18\x02 \x03(\x0b\x32\x13.protos.Data.MEntry\x12\x1a\n\x04strs\x18\x03 \x03(\x0b\x32\x0c.protos.Strs\x12#\n\x06status\x18\x04 \x01(\x0e\x32\x13.protos.Data.Status\x12\x0f\n\x07integer\x18\x05 \x01(\x03\x1a(\n\x06MEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"-\n\x06Status\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\n\n\x06NORMAL\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\"\x13\n\x04Strs\x12\x0b\n\x03str\x18\x01 \x01(\t\"\x1a\n\nDoMicroReq\x12\x0c\n\x04text\x18\x01 \x01(\t\"J\n\x0b\x44oMicroResp\x12\x1a\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0c.protos.Data\x12\x1f\n\x04resp\x18\xff\x01 \x01(\x0b\x32\x10.protos.BaseResp2D\n\x0cMicroService\x12\x34\n\x07\x44oMicro\x12\x12.protos.DoMicroReq\x1a\x13.protos.DoMicroResp\"\x00\x62\x06proto3'
  ,
  dependencies=[protos_dot_base__pb2.DESCRIPTOR,])



_DATA_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='protos.Data.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEFAULT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=236,
  serialized_end=281,
)
_sym_db.RegisterEnumDescriptor(_DATA_STATUS)


_DATA_MENTRY = _descriptor.Descriptor(
  name='MEntry',
  full_name='protos.Data.MEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='protos.Data.MEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='protos.Data.MEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=234,
)

_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='protos.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='protos.Data.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m', full_name='protos.Data.m', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strs', full_name='protos.Data.strs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='protos.Data.status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='integer', full_name='protos.Data.integer', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DATA_MENTRY, ],
  enum_types=[
    _DATA_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=281,
)


_STRS = _descriptor.Descriptor(
  name='Strs',
  full_name='protos.Strs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='protos.Strs.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=302,
)


_DOMICROREQ = _descriptor.Descriptor(
  name='DoMicroReq',
  full_name='protos.DoMicroReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='protos.DoMicroReq.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=330,
)


_DOMICRORESP = _descriptor.Descriptor(
  name='DoMicroResp',
  full_name='protos.DoMicroResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='protos.DoMicroResp.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resp', full_name='protos.DoMicroResp.resp', index=1,
      number=255, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=406,
)

_DATA_MENTRY.containing_type = _DATA
_DATA.fields_by_name['m'].message_type = _DATA_MENTRY
_DATA.fields_by_name['strs'].message_type = _STRS
_DATA.fields_by_name['status'].enum_type = _DATA_STATUS
_DATA_STATUS.containing_type = _DATA
_DOMICRORESP.fields_by_name['data'].message_type = _DATA
_DOMICRORESP.fields_by_name['resp'].message_type = protos_dot_base__pb2._BASERESP
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Strs'] = _STRS
DESCRIPTOR.message_types_by_name['DoMicroReq'] = _DOMICROREQ
DESCRIPTOR.message_types_by_name['DoMicroResp'] = _DOMICRORESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {

  'MEntry' : _reflection.GeneratedProtocolMessageType('MEntry', (_message.Message,), {
    'DESCRIPTOR' : _DATA_MENTRY,
    '__module__' : 'protos.micro_service_pb2'
    # @@protoc_insertion_point(class_scope:protos.Data.MEntry)
    })
  ,
  'DESCRIPTOR' : _DATA,
  '__module__' : 'protos.micro_service_pb2'
  # @@protoc_insertion_point(class_scope:protos.Data)
  })
_sym_db.RegisterMessage(Data)
_sym_db.RegisterMessage(Data.MEntry)

Strs = _reflection.GeneratedProtocolMessageType('Strs', (_message.Message,), {
  'DESCRIPTOR' : _STRS,
  '__module__' : 'protos.micro_service_pb2'
  # @@protoc_insertion_point(class_scope:protos.Strs)
  })
_sym_db.RegisterMessage(Strs)

DoMicroReq = _reflection.GeneratedProtocolMessageType('DoMicroReq', (_message.Message,), {
  'DESCRIPTOR' : _DOMICROREQ,
  '__module__' : 'protos.micro_service_pb2'
  # @@protoc_insertion_point(class_scope:protos.DoMicroReq)
  })
_sym_db.RegisterMessage(DoMicroReq)

DoMicroResp = _reflection.GeneratedProtocolMessageType('DoMicroResp', (_message.Message,), {
  'DESCRIPTOR' : _DOMICRORESP,
  '__module__' : 'protos.micro_service_pb2'
  # @@protoc_insertion_point(class_scope:protos.DoMicroResp)
  })
_sym_db.RegisterMessage(DoMicroResp)


_DATA_MENTRY._options = None

_MICROSERVICE = _descriptor.ServiceDescriptor(
  name='MicroService',
  full_name='protos.MicroService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=408,
  serialized_end=476,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoMicro',
    full_name='protos.MicroService.DoMicro',
    index=0,
    containing_service=None,
    input_type=_DOMICROREQ,
    output_type=_DOMICRORESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MICROSERVICE)

DESCRIPTOR.services_by_name['MicroService'] = _MICROSERVICE

# @@protoc_insertion_point(module_scope)
